config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :moments do
    resources :bookings
  end

  get "match", to: "pages#match"

  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :moment
  belongs_to :user

  validates :moment, presence: true
  validates :user, presence: true
end

app/models/moment.rb
class Moment < ApplicationRecord
  belongs_to :user

  has_many :bookings

  validates :activity, presence: true
  validates :user, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :level, presence: true

  geocoded_by :location
   after_validation :geocode, if: :will_save_change_to_location?

   include PgSearch
   pg_search_scope :search_by_activity_and_location,
     against: [ :activity, :location, :category ],
     using: {
       tsearch: { prefix: true }
     }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :moments
  has_many :bookings
  has_many :activities, through: :moments

  validates :username, presence: true, uniqueness: true
  validates :last_name, presence: true
  validates :first_name, presence: true

  mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_params, only: [:show]
  def index
    @bookings = Booking.where(moment_id: params[:moment_id].to_i)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @moment = Moment.find(params[:moment_id])
    @booking = Booking.new
  end

  def create
    @moment = Moment.find(params[:moment_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.moment = @moment
    if Booking.where(user_id: current_user, moment_id: @moment.id).empty? && @moment.user_id != current_user.id
      @booking.save
      redirect_to moment_path(@moment)
    else
      redirect_to moment_path(@moment)
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:moment_id, :user_id, :description)
  end
end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    if params[:query].present?
      @moments = Moment.search_by_activity_and_location(params[:query])
    else
      @moments = Moment.all
    end

    @markers = @moments.map do |moment|
      {
        lat: moment.latitude,
        lng: moment.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def show
    @booking = Booking.new
    @moment = Moment.find(params[:id])
    @bookings = Booking.where(moment_id: @moment.id)
    @formatted_start = DateTime.parse(@moment.start_time).strftime('%d %b at %H:%M')
    @formatted_end = DateTime.parse(@moment.end_time).strftime('%d %b at %H:%M')

    @moments = Moment.where.not(latitude: nil, longitude: nil)

    @markers = [{
        lat: @moment.latitude,
        lng: @moment.longitude#,
      }]
  end

  def new
    @moment = Moment.new
  end

  def create
    @moment = Moment.new(moment_params)
    @moment.user = current_user
    if @moment.save
      redirect_to moment_path(@moment)
    else
      render :new
    end
  end

  def edit
    @user = current_user
    @moment = Moment.find(params[:id])
    if @moment.user == @user
      return @moment
    else
      render :show
    end
  end

  def update
    @moment = Moment.find(params[:id])
    @moment.update(moment_params)
    redirect_to moment_path(@moment)
  end

  def destroy
    @moment = Moment.find(params[:id])
    if @moment.user == current_user
      @moment.destroy
      redirect_to moments_path
    else
    render "new"
    end
  end

  private

  def moment_params
    params.require(:moment).permit(:category, :activity, :user_id, :description, :location, :level, :start_time, :end_time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
    @user = current_user
    @matching_user = User.all.shuffle[0..0]
  end

  def match
    @user = current_user
    @matching_user = User.all.shuffle[0..0]
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :matching ]

  def show
    @user = User.find(params[:id])
    if @user == current_user
      @bookings = Booking.where(user_id: @user.id)
    else
      @bookings = Array.new
    end
  end

  def edit
    if @user == current_user
      @user
    else
      render :show
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private

  def set_user
   @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :photo, :description, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container">

  <h2>All the bookings for this moment</h2>
  <ul class="list-unstyled">
    <% @bookings.each do |booking| %>
     <li> <%= booking.user.username %> </li>
    <% end %>
  </ul>
  <%= link_to 'Back to Moments List', moments_path, class: 'btn btn-info' %>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="form-container">
    <div class="form-content">

      <h1>Join This Moment</h1>
      <!-- <p>Find me in app/views/flats/new.html.erb</p> -->

      <%= simple_form_for [@moment, @booking] do |f| %>
        <%= f.input :description %>
        <%= f.submit "Join", class: "btn btn-success" %>
        <%= link_to 'Back to Moments List', moments_path, class: 'btn btn-info' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

<div class="container">

  <% @booking %>
    <%= @booking.description %>
    <%= @booking.moment_id.description %>
    <%= @booking.user_id.username %>
    <%= @user.rating %>

<% end %>

link_to "Back to bookings", booking_path

</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>book a friend for anything</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
  </head>
  <body>
    <%= render'shared/navbar' %>
     <%= render'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
  </body>
</html>

app/views/moments/create.html.erb
<h1>Moments#create</h1>
<p>Find me in app/views/moments/create.html.erb</p>

app/views/moments/destroy.html.erb
<h1>Moments#destroy</h1>
<p>Find me in app/views/moments/destroy.html.erb</p>

app/views/moments/show.html.erb
<div class="container moment-container">
  <div class="moment-main-info">

    <!-- left column images + join button -->
    <div id="moment-category">
      <div id="img-img">
        <%= image_tag "#{@moment.category.downcase}.jpg" %>
        <div id="moment-user-img">
          <%= link_to user_path(@moment.user) do %>
            <% if @moment.user.photo.file.nil?%>
              <%= image_tag "avatar-baf.png", height: 80, width: 80, class: "img-circle" %>
            <% else %>
              <%= cl_image_tag @moment.user.photo, height: 80, width: 80, crop: :fill, class: "img-circle" %>
            <% end %>
          <% end %>
        </div>
        <div id="moment-user-participants">
          <h3>Participants</h3>
          <% @bookings.each do |booking| %>
            <%= link_to user_path(booking.user) do %>
              <div class="one-booking"><%= cl_image_tag booking.user.photo, height: 60, width: 60, crop: :fill, class: "img-circle" %></div>
            <% end %>
          <% end %>
        </div>
      </div>
      <!-- Button trigger modal -->
      <% if @moment.user != current_user %>
        <button type="button" id="img-join" data-toggle="modal" data-target="#joinModal">
          Join this moment
        </button>
      <% end %>
    </div>

    <!-- right column = basic infos -->
    <div id="moment-content">
      <div id="moment-user-content">
        <div id="moment-activity">
          <h1><%= @moment.activity %></h1>
        </div>
        <% countdown = (@moment.start_time.to_date - Date.today).to_i %>
        <% if countdown < 0 %>
          <div id="countdown-expired">
            <p id="expired">Too late, sorry!</p>
          </div>
        <% elsif countdown == 0 %>
          <div id="countdown">
            <p>That's today!</p>
          </div>
        <% elsif countdown == 1 %>
          <div id="countdown">
            <p>Starts in <%= countdown %> day</p>
          </div>
        <% elsif countdown > 3 %>
          <div id="countdown-cool">
            <p>Starts in <%= countdown %> days</p>
          </div>
        <% else %>
          <div id="countdown">
            <p>Starts in <%= countdown %> days</p>
          </div>
        <% end %>
        <div class="nav-buttons-show">
          <% if @moment.user == current_user %>
            <%= link_to 'Edit', edit_moment_path %>
            <%= link_to 'Delete', moment_path, method: :delete %>
          <% end %>
        </div>
        <div class="moment-user-insides" id="moment-date">
          <div id="moment-start">
            <%= @formatted_start %> - <%= @formatted_end %>
          </div>
        </div>
        <div class="moment-user-insides" id="moment-description">
          <%= @moment.description %>
        </div>
        <div id="location-div">
          <div class="moment-user-insides" id="moment-location">
            <a href="#map-contain"><i class="fas fa-map-marker"></i> <%= @moment.location %></a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- full width end of page -->
  <div class="full-width-end">
    <div class="moment-messages">
      <h4>Check who's in</h4>
      <% @moment.bookings.each do |booking| %>
        <div class="one-message">
          <span><%= cl_image_tag booking.user.photo, height: 60, width: 60, crop: :fill, class: "img-circle" %></span><span class="booking-description"><%= booking.description %></span> - <span class="booking-user"><%= booking.user.first_name %></span>
        </div>
      <% end %>
    </div>
    <div id="map-contain">
      <h4>Where is it?</h4>
      <div id="map" style="width: 100vw; height: 520px;" data-markers="<%= @markers.to_json %>"></div>
    </div>
  </div>
</div>


<!-- join modal -->

<div class="modal fade" id="joinModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Join this moment</h4>
      </div>
      <div class="modal-body">
        <% if @moment.user != current_user %>
          <div class="form-container">
            <div class="form-content">
              <%= simple_form_for [@moment, @booking] do |f| %>
                <%= f.input :description, label: "Say something to #{@moment.user.first_name}" %>
                <%= f.submit "Join", class: "btn btn-success" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/moments/update.html.erb
<h1>Moments#update</h1>
<p>Find me in app/views/moments/update.html.erb</p>


link_to "Back to moments", index_path

app/views/pages/home.html.erb
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(20,20,20,0.6) 0%, rgba(20,20,20,0.6) 50%), url('https://res.cloudinary.com/drq2pi5ow/image/upload/v1542105515/Penguin-Wallpaper-In-High-Definition-.jpg');">
  <div class="banner-content">
    <div id="main-title">New city buddy<span id="space"> </span><span class="js-text js-text5">to do anything</span></div>
    <div class="forms-search" id="form-form">
      <div>
        <%= form_tag moments_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id:"form-start",
            placeholder: "Search for your next buddy"
          %>
      </div>
      <div>
        <%= button_tag "Search" , class: "btn-search"%>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%=  link_to 'match', match_path, class: "btn-search" %>
      <% end %>
    </div>
  </div>
</div>

<!-- Pricing -->
<section id="pricing" class="pricing section">
    <div class="container">
        <div class="row">
            <div class="col-10 col-lg-12 mx-auto">
                <div class="row">
                    <div class="col">
                        <h2 class="lg-font-size font-weight__500 text-center">
                Pricing
              </h2>
                    </div>
                </div>
                <!-- Empty Space -->
                <div class="md-space"></div>
                <!-- Emty Space -->
                <div class="row">
                    <div class="col-12 mx-auto">
                        <div class="row">
                            <div class="col-12 col-lg-4 pricing-wrap box box-shadow rounded p-3 my-3 my-lg-5">
                                <div class="pricing-inner text-center p-5 p-md-3 p-xl-5">
                                    <h3 class="pricing-inner__title lg-font-size">Basic Buddy</h3>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <div class="pricing-inner__price price">
                                        <span class="price__amount d-inline-block">€25</span> <span class="d-inline-block"> <span class="price__currency xl-font-size d-block font-weight__900">EUR</span> <span class="price__time sm-font-size">1-day engagement</span></span>
                                    </div>
                                    <div class="pricing-inner__info"><span>3 hours buddy presence</span></div>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <ul class="pricing-inner__list list-unstyled sm-font-size">
                                        <li><span class="text-success"><i class="fa fa-check"></i></span> Meet your buddy for a drink, lunch or dinner at a common place</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> The buddy can help you with local city information</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> Fusce in venenatis ligula</li>
                                    </ul>
                                    <div class="col text-center mt-md-5">
                                        <a href="#" class="btn btn-lg btn-primary px-md-5">Get Now</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-4 active pricing-wrap box box-shadow my-3 my-lg-0">
                                <div class="pricing-inner text-center p-5 p-md-3 p-xl-5">
                                    <h3 class="pricing-inner__title lg-font-size">Accommodation Buddy</h3>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <div class="pricing-inner__price price">
                                        <span class="price__amount d-inline-block">€25</span> <span class="d-inline-block"> <span class="price__currency xl-font-size d-block font-weight__900">EUR</span> <span class="price__time sm-font-size">one-time</span></span>
                                    </div>
                                    <div class="pricing-inner__info"><span>1 person</span></div>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <ul class="pricing-inner__list list-unstyled sm-font-size">
                                        <li><span class="text-success"><i class="fa fa-check"></i></span> Helping the newcomer to find an accommodation in the city</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> Meetings – Information about localities, price ranges, making phone calls - €15/meeting</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> Buddy accompanied Visits - €15/hour
</li>
                                    </ul>
                                    <div class="col text-center mt-md-5">
                                        <a href="#" class="btn btn-lg btn-secondary px-md-5">Buy Now</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-4 pricing-wrap box box-shadow rounded p-3 my-3 my-lg-5">
                                <div class="pricing-inner text-center p-5 p-md-3 p-xl-5">
                                    <h3 class="pricing-inner__title lg-font-size">City Tour Buddy</h3>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <div class="pricing-inner__price price">
                                        <span class="price__amount d-inline-block">€40</span> <span class="d-inline-block"> <span class="price__currency xl-font-size d-block font-weight__900">EUR</span> <span class="price__time sm-font-size">one time</span></span>
                                    </div>
                                    <div class="pricing-inner__info"><span>Visiting tourist spots within the city</span></div>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <ul class="pricing-inner__list list-unstyled sm-font-size">
                                        <li><span class="text-success"><i class="fa fa-check"></i></span> €20/person - 2 hour-tour</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> €40/person - 4 hour-tour</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> €60/person - 6 hour-tour</li>
                                    </ul>
                                    <div class="col text-center mt-md-5">
                                        <a href="#" class="btn btn-lg btn-primary px-md-5">Get Now</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-12 pricing-wrap active box box-shadow rounded p-3 my-3 my-lg-5">
                                <div class="pricing-inner text-center p-5 p-md-3 p-xl-5">
                                    <h3 class="pricing-inner__title lg-font-size">Hired buddy</h3>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <div class="pricing-inner__price price">
                                        <span class="price__amount d-inline-block">€15</span> <span class="d-inline-block"> <span class="price__currency xl-font-size d-block font-weight__900">EUR</span> <span class="price__time sm-font-size">or €50 annually</span></span>
                                    </div>
                                    <div class="pricing-inner__info"><span>Random Requests</span></div>
                                    <!-- Empty Space -->
                                    <div class="md-space"></div>
                                    <!--/ End Empty Space -->
                                    <ul class="pricing-inner__list list-unstyled sm-font-size">
                                        <li><span class="text-success"><i class="fa fa-check"></i></span>Vehicle service - pick up, lift, big items transportation</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> Grocery/food/drink delivery - look for buddies in a certain area or store to bring stuff</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> I.T. help - look for I.T. specialists to deal with computer/phone issues</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> Translator - need a buddy who speaks a certain language</li>
                                        <li><span><i class="text-success fa fa-check"></i></span> Educational advice - need help with school assignments</li>
                                    </ul>
                                    <div class="col text-center mt-md-5">
                                        <a href="#" class="btn btn-lg btn-primary px-md-5">Get Now</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/pages/match.html.erb
<div class="container data-file">
  <!-- basic info -->
  <div class="show-user-img">
    <% if @user.photo.file.nil?%>
      <%= image_tag "avatar-baf.png", height: 120, width: 120 %>
    <% else %>
      <%= cl_image_tag @user.photo, height: 120, width: 120, crop: :fill, class: "img-circle" %>
    <% end %>
  </div>
  <div class="user-profile">
    <div class="row row-user">
      <div id="show-username">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      </div>
      <div id="user-data">
        <div>
          <% if @user.rating.nil? %>
            <i class="far fa-star"></i>
          <% else %>
            <% @user.rating.times do %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        </div>
        <% if @user == current_user %>
          <div id="edit-bio">
            <%= link_to "Edit your bio", edit_user_path(@user) %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- description -->
    <div class="row" id="user-description">
      <h2>About me</h2>
      <%= @user.description %>
    </div>
  </div>

  <div class="show-user-img">
    <% if @matching_user[0].photo.file.nil?%>
      <%= image_tag "avatar-baf.png", height: 120, width: 120 %>
    <% else %>
      <%= cl_image_tag @matching_user[0].photo, height: 120, width: 120, crop: :fill, class: "img-circle" %>
    <% end %>
  </div>
  <div class="user-profile">
    <div class="row row-user">
      <div id="show-username">
        <h1><%= @matching_user[0].first_name %> <%= @matching_user[0].last_name %></h1>
      </div>
      <div id="user-data">
        <div>
          <% if @matching_user[0].rating.nil? %>
            <i class="far fa-star"></i>
          <% else %>
            <% @matching_user[0].rating.times do %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- description -->
    <div class="row" id="user-description">
      <h2>About me</h2>
      <%= @matching_user[0].description %>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="logo">
    <%= link_to root_path do %>
      <h1>New City Buddy</h1>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

<!--       <a href="" class="navbar-wagon-item navbar-wagon-link">My Moments</a> -->
    <% if user_signed_in? %>
      <%= link_to 'My Bookings', user_path(current_user), class: 'btn btn-default btn-nav' %>
    <% end %>
      <%= link_to 'Add a Moment', new_moment_path, class: 'btn btn-primary btn-nav' %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
          <div data-toggle="dropdown">
            <%= cl_image_tag(current_user.photo, :width => 50, :height => 50, class: 'img-circle dropdown-toggle', id: 'navbar-wagon-menu') %>
          </div>
        <% else %>
          <img src="http://www.kvchostingreview.com/images/user-256x256.png" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
            <%= t(".sign_out", default: 'Log Out') %>
            <% end %></li>
        <% else %>
          <li><%= link_to new_user_session_path do %>
           <%= t(".sign_out", default: 'Sign In') %>
          <% end %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
            <%= t(".sign_out", default: 'Log Out') %>
            <% end %></li>
        <% else %>
          <li><%= link_to new_user_session_path do %>
           <%= t(".sign_out", default: 'Sign In') %>
          <% end %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/_card.html.erb
<%= link_to moment_path(booking.moment) do %>
  <div class="col-xs-12 col-sd-6 col-md-4 booking-card">
      <div class="booking-content" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path "#{booking.moment.category.downcase}.jpg"%>); background-size: cover; border-radius: 4px; '>
      <div id="booking-activity">
        <%= booking.moment.activity %>
      </div>
      <div id="booking-location">
        <i class="fas fa-map-marker"></i> <%= booking.moment.location %>
      </div>
    </div>
<% end %>
  <div id="delete">
  <% if booking.user == current_user %>
    <%= link_to 'Delete Booking', moment_booking_path(booking.moment, booking), method: :delete %>
  <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="photo-background">
  <div class="container">
    <div class="row">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container data-file">
  <!-- basic info -->
  <div class="show-user-img">
    <% if @user.photo.file.nil?%>
      <%= image_tag "avatar-baf.png", height: 120, width: 120 %>
    <% else %>
      <%= cl_image_tag @user.photo, height: 120, width: 120, crop: :fill, class: "img-circle" %>
    <% end %>
  </div>
  <div class="user-profile">
    <div class="row row-user">
      <div id="show-username">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      </div>
      <div id="user-data">
        <div>
          <% if @user.rating.nil? %>
            <i class="far fa-star"></i>
          <% else %>
            <% @user.rating.times do %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        </div>
        <% if @user == current_user %>
          <div id="edit-bio">
            <%= link_to "Edit your bio", edit_user_path(@user) %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- description -->
    <div class="row" id="user-description">
      <h2>About me</h2>
      <%= @user.description %>
    </div>

    <!-- activities involved -->
    <div class="row">
      <h2>Next events for <%= @user.first_name %></h2>
        <% @bookings.each do |booking| %>
          <%= render 'card', booking: booking %>
        <% end %>
    </div>

    <!-- my moments -->
    <div class="row">
      <h2>Next moments organized by <%= @user.first_name %></h2>
      <% @user.moments.each do |moment| %>
        <%= link_to moment_path(moment) do %>
          <div class="col-xs-12 col-sd-6 col-md-4 my-moments-card">
            <div class="moment-content" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_path "#{moment.category.downcase}.jpg"%>); background-size: cover; border-radius: 4px; '>
              <div id="moment-activity">
                <%= moment.activity %>
              </div>
              <div id="moment-location">
                <i class="fas fa-map-marker"></i> <%= moment.location %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>